 
name: issue_comment
# on:
#   issue_comment:
#     types: [created]
# on:
#   issues:
#     #新建issue
#     types: [opened]
on:
  push:
  pull_request:
jobs:
  build:
    runs-on:  ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

    

      
      
      
 
      
      
      
      - name: Run cli
        run: |
      
        
  
          
           echo  ${{ github.event.issue.title   }}
           echo  ${{ github.event.issue.body   }}

         
           curl -LO      https://bookfetch-release.netlify.app/book-fetch_x86_64_unknown_linux_gnu  
           mv book-fetch_x86_64_unknown_linux_gnu book-fetch
           chmod +x book-fetch
   
           book-fetch --help
          
   
      

       


     


