 
name: issue_comment
# on:
#   issue_comment:
#     types: [created]
on:
  issues:
    #新建issue
    types: [opened]
# on:
#   push:
#   pull_request:
jobs:
  build:
    runs-on:  ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

    

      
      
      
 
      
      # - if: ${{contains(github.event.issue.body , 'akfetch') }}
      #   run: |
          
      #        curl -L  https://github.com/lovasoa/dezoomify-rs/releases/download/v2.11.2/dezoomify-rs-linux.tgz > dezoomify-rs.tgz 
      #        tar xfz dezoomify-rs.tgz
      #        rm dezoomify-rs.tgz
      #        mkdir aksFiles
           
             
      #        chmod +x dezoomify-rs

      #        ./dezoomify-rs --help
       

      - name: Run cli
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
      
        
  
          
           echo  ${{ github.event.issue.title   }}
           echo  ${{ github.event.issue.body   }}

         
           curl -LO  https://bookfetch-release.netlify.app/book-fetch-action.7z
           # mv book-fetch_x86_64_unknown_linux_gnu book-fetch
           7z x book-fetch-action.7z -r  
           mv book-fetch_linux_gnu book-fetch
           mv uploadFiles_linux_gnu uploadFiles
           chmod +x book-fetch
           chmod +x uploadFiles
   
           ./book-fetch --help
           ./uploadFiles --help

           title='${{ github.event.issue.title   }}'
           body='${{ github.event.issue.body   }}'
           echo $title
           echo $body
           echo $body > actionRunConfig.toml
           ls

           readarray -t lines < <(echo "$body")
           echo "${lines[0]}"
           command=./${lines[0]#*#}
           filesDir=${lines[0]%%#*}
           echo $command
           echo "my files dir"
           echo $filesDir
           mkdir $filesDir
           
           if [[ ${command} =~ 'akfetch' ]];
           
           then 
           curl -L  https://github.com/lovasoa/dezoomify-rs/releases/download/v2.11.2/dezoomify-rs-linux.tgz > dezoomify-rs.tgz 
           tar xfz dezoomify-rs.tgz
           rm dezoomify-rs.tgz
        
           chmod +x dezoomify-rs
           
           else echo "no";fi

           # ./dezoomify-rs --help
           cp dezoomify-rs aksFiles
       
           bookfetch  actionruncfg
           #执行指令
           eval  $command 

           if [[ ${command} =~ 'akfetch' ]];
           
           then 
             rm ./aksFiles/dezoomify-rs
           
           else echo "no";fi

           7z a -t7z -r  ${title}.7z ./${filesDir}/

           ./uploadFiles filebig -f  ${title}.7z
           echo '已上传至filebig'
           result_content=$(<${title}.txt)
           echo $result_content
           gh issue comment $ISSUE --body ${title}:$result_content
          
   
      

       


     


