 
name: issue_comment
# on:
#   issue_comment:
#     types: [created]
on:
  issues:
    #新建issue
    types: [opened]
jobs:
  build:
    runs-on:  ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

    

      
      
      
 
      
      
      
      - name: Run cli
        run: |
      
        
  
          
           echo  ${{ github.event.issue.title   }}
           echo  ${{ github.event.issue.body   }}
     
          

      

       


     


