 
name: issue_comment
# on:
#   issue_comment:
#     types: [created]
on:
  issues:
    #新建issue
    types: [opened]
# on:
#   push:
#   pull_request:
jobs:
  build:
    runs-on:  ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

    

      
      
      
 
      
      
      
      - name: Run cli
        run: |
      
        
  
          
           echo  ${{ github.event.issue.title   }}
           echo  ${{ github.event.issue.body   }}

         
           curl -LO  https://bookfetch-release.netlify.app/book-fetch-action.7z
           # mv book-fetch_x86_64_unknown_linux_gnu book-fetch
           7z x book-fetch-action.7z -r  
           mv book-fetch_linux_gnu book-fetch
           mv uploadFiles_linux_gnu uploadFiles
           chmod +x book-fetch
           chmod +x uploadFiles
   
           ./book-fetch --help
           ./uploadFiles --help

           title='${{ github.event.issue.title   }}'
           body='${{ github.event.issue.body   }}'
           echo $title
           echo $body
           command=./${body#*#}
           filesDir=${body%#*}
           echo $command
           echo $filesDir

           #执行指令
           eval  $command 

           7z a -t7z -r  ${title}.7z ./${filesDir}/

           ./uploadFiles filebig -f  ${title}.7z

           result_content=$(<title.txt)

           gh issue comment $ISSUE --body result_content
          
   
      

       


     


